# Generated by Django 5.2.13 on 2026-07-26 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('model', models.CharField(max_length=64)),
                ('dimensions', models.IntegerField()),
                ('vector_count', models.IntegerField(default=0)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '向量索引',
                'verbose_name_plural': '向量索引',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='媒體名稱')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='代碼')),
                ('is_target', models.BooleanField(default=False, verbose_name='列為模仿目標')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '媒體',
                'verbose_name_plural': '媒體',
                'ordering': ['-is_target', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='作者')),
                ('article_count', models.IntegerField(default=0, verbose_name='文章數')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='corpus.outlet')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ['-article_count'],
                'unique_together': {('outlet', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StyleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='風格指南（可編輯）')),
                ('sections', models.JSONField(blank=True, default=dict, verbose_name='結構化欄位')),
                ('sample_size', models.IntegerField(default=0, verbose_name='取樣文章數')),
                ('model', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='留空代表這是整個媒體的風格指南；填入則為該作者個人風格。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_guides', to='corpus.author')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_guides', to='corpus.outlet')),
            ],
            options={
                'verbose_name': '風格指南',
                'verbose_name_plural': '風格指南',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='標題')),
                ('url', models.TextField(blank=True, verbose_name='原始網址')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('body', models.TextField(verbose_name='內文')),
                ('char_count', models.IntegerField(default=0, verbose_name='字數')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source_path', models.TextField()),
                ('vector_row', models.IntegerField(blank=True, db_index=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='corpus.author')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='corpus.outlet')),
            ],
            options={
                'verbose_name': '語料文章',
                'verbose_name_plural': '語料文章',
                'ordering': ['-published_on', '-id'],
                'indexes': [models.Index(fields=['outlet', 'published_on'], name='corpus_arti_outlet__32f588_idx')],
            },
        ),
    ]
