# Generated by Django 6.0.4 on 2026-08-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["outlet", "char_count", "vector_row"],
                name="corpus_arti_outlet__39b0cd_idx",
            ),
        ),
    ]
