# Generated by Django 5.2.13 on 2026-08-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0002_article_corpus_arti_outlet__39b0cd_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-published_on", "-id"], name="corpus_article_recent_idx"
            ),
        ),
    ]
