# Generated by Django 5.2.13 on 2026-07-26 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefs', '0001_initial'),
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='實驗名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'A/B 實驗',
                'verbose_name_plural': 'A/B 實驗',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieval_strategy', models.CharField(choices=[('topical', '主題相似檢索（依簡報內容找同題材範文）'), ('random', '隨機抽樣（同媒體/作者內隨機）'), ('hybrid', '混合（一半主題相似、一半隨機）'), ('none', '不放範例（只用風格指南）')], default='topical', max_length=16, verbose_name='檢索策略')),
                ('exemplar_count', models.IntegerField(default=4, verbose_name='範例篇數')),
                ('exemplars', models.JSONField(blank=True, default=list, help_text='[{id, title, score, author}]', verbose_name='實際使用的範例')),
                ('prompt_instructions', models.TextField(blank=True)),
                ('prompt_input', models.TextField(blank=True)),
                ('output', models.TextField(blank=True, verbose_name='生成結果')),
                ('model', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', '待執行'), ('running', '生成中'), ('done', '完成'), ('failed', '失敗')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('elapsed_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='corpus.author', verbose_name='目標作者（可留空）')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='briefs.brief')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='studio.experiment')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='corpus.outlet')),
                ('style_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='corpus.styleguide')),
            ],
            options={
                'verbose_name': '生成紀錄',
                'verbose_name_plural': '生成紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=2, verbose_name='稿次')),
                ('feedback', models.TextField(verbose_name='修改意見')),
                ('output', models.TextField(blank=True, verbose_name='修訂後內容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='studio.generationrun')),
            ],
            options={
                'verbose_name': '修訂稿',
                'verbose_name_plural': '修訂稿',
                'ordering': ['round'],
                'unique_together': {('run', 'round')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_similarity', models.FloatField(blank=True, help_text='與目標媒體語料重心的 cosine，越高越像', null=True, verbose_name='風格向量相似度')),
                ('exemplar_similarity', models.FloatField(blank=True, null=True, verbose_name='與所用範例的相似度')),
                ('max_overlap', models.FloatField(blank=True, help_text='抄襲防護：過高代表照抄範文', null=True, verbose_name='與範例最大字串重疊率')),
                ('overlap_source', models.CharField(blank=True, max_length=512)),
                ('fact_coverage', models.JSONField(blank=True, default=dict, verbose_name='事實覆蓋檢查')),
                ('judge_scores', models.JSONField(blank=True, default=dict, verbose_name='LLM 評審分數')),
                ('judge_comment', models.TextField(blank=True, verbose_name='LLM 評審意見')),
                ('human_score', models.IntegerField(blank=True, null=True, verbose_name='人工評分 1-5')),
                ('human_comment', models.TextField(blank=True, verbose_name='人工意見')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='studio.generationrun')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='studio.revision')),
            ],
            options={
                'verbose_name': '評估結果',
                'verbose_name_plural': '評估結果',
                'ordering': ['-created_at'],
            },
        ),
    ]
