# Generated by Django 5.2.13 on 2026-07-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('a', 'A 較佳'), ('b', 'B 較佳'), ('tie', '平手／不一致')], default='tie', max_length=4)),
                ('position_consistent', models.BooleanField(default=False, help_text='False 代表模型只是偏好排在前面的稿件，該結果不可採信。', verbose_name='兩種順序判斷一致')),
                ('dimension_winners', models.JSONField(blank=True, default=dict, verbose_name='各維度勝方')),
                ('reasoning', models.TextField(blank=True, verbose_name='評審理由')),
                ('model', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='studio.experiment')),
                ('run_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='studio.generationrun')),
                ('run_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='studio.generationrun')),
            ],
            options={
                'verbose_name': '兩兩對比評審',
                'verbose_name_plural': '兩兩對比評審',
                'ordering': ['-created_at'],
            },
        ),
    ]
