# Generated by Django 5.2.13 on 2026-07-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_pairwisecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='mode',
            field=models.CharField(choices=[('single', '方案 A：單次生成'), ('staged', '方案 B：多階段管線（檢索→重排→摘要→大綱→生成）')], default='single', max_length=8, verbose_name='生成方式'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='notes',
            field=models.TextField(blank=True, verbose_name='重點筆記（摘要階段產出）'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='outline',
            field=models.TextField(blank=True, verbose_name='大綱（可在生成正文前人工修改）'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='outline_approved',
            field=models.BooleanField(default=False, verbose_name='大綱已確認'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='stages',
            field=models.JSONField(blank=True, default=list, verbose_name='各階段紀錄'),
        ),
        migrations.AlterField(
            model_name='generationrun',
            name='retrieval_strategy',
            field=models.CharField(choices=[('topical', '主題相似檢索（依簡報內容找同題材範文）'), ('random', '隨機抽樣（同媒體/作者內隨機）'), ('hybrid', '混合（一半主題相似、一半隨機）'), ('typical', '主題檢索後依「文體代表性」重排（方案 B 預設）'), ('none', '不放範例（只用風格指南）')], default='topical', max_length=16, verbose_name='檢索策略'),
        ),
    ]
