# Generated by Django 5.2.13 on 2026-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_generationrun_mode_generationrun_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='mode',
            field=models.CharField(choices=[('staged', '方案 B：多階段管線（檢索→重排→摘要→大綱→生成）'), ('single', '方案 A：單次生成（較快，結構較鬆）')], default='staged', max_length=8, verbose_name='生成方式'),
        ),
        migrations.AlterField(
            model_name='generationrun',
            name='retrieval_strategy',
            field=models.CharField(choices=[('topical', '主題相似檢索（依簡報內容找同題材範文）'), ('random', '隨機抽樣（同媒體/作者內隨機）'), ('hybrid', '混合（一半主題相似、一半隨機）'), ('typical', '主題檢索後依「文體代表性」重排（方案 B 預設）'), ('none', '不放範例（只用風格指南）')], default='typical', max_length=16, verbose_name='檢索策略'),
        ),
    ]
