# Generated by Django 5.2.13 on 2026-07-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_generationrun_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='max_iterations',
            field=models.IntegerField(default=2, help_text='1 = 只寫一次；2 = 初稿＋依評審意見自動重寫一次。上限 4。', verbose_name='生成次數 n'),
        ),
        migrations.AddField(
            model_name='revision',
            name='accepted',
            field=models.BooleanField(default=True, verbose_name='採納為目前最佳稿'),
        ),
        migrations.AddField(
            model_name='revision',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='未採納原因'),
        ),
        migrations.AddField(
            model_name='revision',
            name='source',
            field=models.CharField(choices=[('human', '人工意見'), ('auto', 'LLM 評審意見（自動重寫）')], default='human', max_length=8, verbose_name='意見來源'),
        ),
        migrations.AlterField(
            model_name='generationrun',
            name='retrieval_strategy',
            field=models.CharField(choices=[('topical', '主題相似檢索（依簡報內容找同題材範文）'), ('random', '隨機抽樣（同媒體/作者內隨機）'), ('hybrid', '混合（一半主題相似、一半隨機）'), ('typical', '主題檢索後依「文體代表性」重排（預設）'), ('none', '不放範例（只用風格指南）')], default='typical', max_length=16, verbose_name='檢索策略'),
        ),
    ]
