# Generated by Django 5.2.13 on 2026-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_generationrun_max_iterations_revision_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='status',
            field=models.CharField(choices=[('pending', '待執行'), ('running', '生成中'), ('refining', '自動重寫中'), ('done', '完成'), ('failed', '失敗')], default='pending', max_length=16),
        ),
    ]
