# Generated by Django 6.0.4 on 2026-07-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0006_brieffacts"),
        ("studio", "0008_generationrun_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retrieval_strategy",
                    models.CharField(
                        choices=[
                            ("topical", "主題相似檢索（依簡報內容找同題材範文）"),
                            ("typical", "主題檢索後依「文體代表性」重排"),
                            ("none", "不放範例（只用風格指南）"),
                            ("random", "隨機抽樣（同媒體/作者內隨機）"),
                            ("hybrid", "混合（一半主題相似、一半隨機）"),
                        ],
                        default="typical",
                        help_text="決定拿哪幾篇該媒體的舊文章當語感範例。實測三種策略產出分不出差異。",
                        max_length=16,
                        verbose_name="檢索策略",
                    ),
                ),
                (
                    "exemplar_count",
                    models.IntegerField(default=4, verbose_name="範例篇數"),
                ),
                (
                    "max_rewrites",
                    models.IntegerField(
                        default=1,
                        help_text="0 = 只寫初稿；1 = 初稿評估後自動重寫一次（預設）。上限 3。",
                        verbose_name="生成評估後重寫次數",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "產稿預設值",
                "verbose_name_plural": "產稿預設值",
            },
        ),
        migrations.AddField(
            model_name="generationrun",
            name="facts_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="briefs.brieffacts",
                verbose_name="採用的事實版本",
            ),
        ),
        migrations.AlterField(
            model_name="generationrun",
            name="retrieval_strategy",
            field=models.CharField(
                choices=[
                    ("topical", "主題相似檢索（依簡報內容找同題材範文）"),
                    ("typical", "主題檢索後依「文體代表性」重排"),
                    ("none", "不放範例（只用風格指南）"),
                    ("random", "隨機抽樣（同媒體/作者內隨機）"),
                    ("hybrid", "混合（一半主題相似、一半隨機）"),
                ],
                default="typical",
                max_length=16,
                verbose_name="檢索策略",
            ),
        ),
    ]
