# Generated by Django 6.0.4 on 2026-08-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0009_sitesettings_generationrun_facts_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="confirm_fact_updates",
            field=models.BooleanField(
                default=False,
                help_text="開啟後，使用者送出更正會先看到前後對照，確認才存成新版本。關閉則直接存成新版本——舊版本都留著，改壞了切回去即可。",
                verbose_name="更正事實前先確認差異",
            ),
        ),
    ]
