# Generated by Django 6.0.4 on 2026-08-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0010_sitesettings_confirm_fact_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="source",
            field=models.CharField(
                choices=[
                    ("human", "人工意見"),
                    ("auto", "LLM 評審意見（自動重寫）"),
                    ("manual", "人工直接編輯"),
                ],
                default="human",
                max_length=8,
                verbose_name="意見來源",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="confirm_fact_updates",
            field=models.BooleanField(
                default=False,
                help_text="開啟後，使用者送出更正會先看到前後對照，確認才存成新版本。關閉則直接存成新版本——舊版本都留著，產稿時可以指定用哪一版。",
                verbose_name="更正事實前先確認差異",
            ),
        ),
    ]
