# Generated by Django 6.0.4 on 2026-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0011_alter_revision_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationrun",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="開始執行時間"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_parallel_runs",
            field=models.IntegerField(
                default=2,
                help_text="產稿改成背景執行後，使用者可以連按好幾次。超過這個數字的會排隊，不會同時打出去。調高會加快多篇產出，也會同時放大 API 用量與SQLite 的寫入競爭。",
                verbose_name="同時產稿上限",
            ),
        ),
    ]
