# Generated by Django 6.0.4 on 2026-08-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0012_generationrun_started_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本")),
                ("text", models.TextField(blank=True, verbose_name="稿件內容")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("generate", "系統產出"),
                            ("manual", "人工直接編輯"),
                            ("revise", "依意見重寫"),
                        ],
                        default="generate",
                        max_length=16,
                        verbose_name="來源",
                    ),
                ),
                (
                    "user_input",
                    models.TextField(blank=True, verbose_name="使用者當時的意見"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="studio.draftversion",
                        verbose_name="以哪一版為基礎",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_versions",
                        to="studio.generationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "稿件版本",
                "verbose_name_plural": "稿件版本",
                "ordering": ["-version"],
                "unique_together": {("run", "version")},
            },
        ),
    ]
