# Generated by Django 6.0.4 on 2026-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0014_seed_draft_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_mode",
            field=models.CharField(
                choices=[
                    ("staged", "方案 B：多階段管線（檢索→重排→摘要→大綱→生成）"),
                    ("single", "方案 A：單次生成（較快，結構較鬆）"),
                ],
                default="staged",
                help_text="「產出廣編稿」預設用哪個方案。方案 B 結構完整度較高但慢，方案 A 較快，兩者的取捨見系統報告書 §七之四。",
                max_length=8,
                verbose_name="預設生成方式",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="llm_backend",
            field=models.CharField(
                choices=[
                    ("online", "線上 API（gpt-5.4，穩定，逐次計費）"),
                    (
                        "local",
                        "本地模型（Ollama，免費，但實測文字生成約 20% 機率耗時拉長5～50 倍、圖片辨識約 30% 機率失敗或給出空白結果，詳見 report/本地線上API比較.md）",
                    ),
                ],
                default="online",
                help_text="只影響寫稿與圖片辨識，評審永遠走線上——避免本地模型評自己的稿子。",
                max_length=8,
                verbose_name="文字／圖片生成使用的 API",
            ),
        ),
    ]
