# Generated by Django 6.0.4 on 2026-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0015_sitesettings_default_mode_sitesettings_llm_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="llm_backend",
            field=models.CharField(
                choices=[
                    ("online", "線上 API，使用 gpt-5.4"),
                    (
                        "local",
                        "本地模型，文字用 qwen3.6:27b-q4_K_M、圖片用 qwen3-vl:32b-fast",
                    ),
                ],
                default="online",
                help_text="只影響寫稿與圖片辨識，評審永遠走線上——避免本地模型評自己的稿子。",
                max_length=8,
                verbose_name="文字／圖片生成使用的 API",
            ),
        ),
    ]
