# Generated by Django 5.2.13 on 2026-08-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0016_alter_sitesettings_llm_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="llm_backend",
            field=models.CharField(
                choices=[("online", "線上 API"), ("local", "本地模型")],
                default="online",
                help_text="只影響寫稿與圖片辨識，評審永遠走線上——避免本地模型評自己的稿子。",
                max_length=8,
                verbose_name="文字／圖片生成使用的 API",
            ),
        ),
    ]
