# Generated by Django 5.2.13 on 2026-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0017_alter_sitesettings_llm_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="show_briefs_nav",
            field=models.BooleanField(
                default=True,
                help_text="關掉只是收起導覽連結。後台看得到所有使用者的專案，前台只看得到自己的。",
                verbose_name="後台顯示「專案」",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_runs_nav",
            field=models.BooleanField(
                default=True,
                help_text="關掉只是收起導覽連結。失敗的稿件只有這裡看得到，前台一律不顯示。",
                verbose_name="後台顯示「生成紀錄」",
            ),
        ),
    ]
