# Generated by Django 5.2.13 on 2026-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0018_sitesettings_show_briefs_nav_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="embed_device",
            field=models.CharField(
                choices=[
                    ("cuda", "GPU（快，但佔 ~2.3GB VRAM）"),
                    ("cpu", "CPU（釋出 VRAM 給生成模型；查詢只慢 ~44ms）"),
                ],
                default="cuda",
                help_text="嵌入模型（BGE-M3）跑在 GPU 還是 CPU。放 CPU 可騰出 ~2.3GB VRAM 給文字/圖片模型共存，查詢僅慢約 44 毫秒；只有重建整個語料索引會明顯變慢。",
                max_length=8,
                verbose_name="本地嵌入模型執行裝置",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ollama_idle_unload_minutes",
            field=models.IntegerField(
                default=3,
                help_text="本地模型在最後一次使用後，閒置這麼多分鐘就從 VRAM 卸載。0 = 用完立即卸載（每次都要重新載入，會很慢）；預設 3。上限 120。",
                verbose_name="本地模型閒置卸載（分鐘）",
            ),
        ),
    ]
