# Generated by Django 5.2.13 on 2026-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0019_sitesettings_embed_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="upload_max_batch_mb",
            field=models.IntegerField(
                default=600,
                help_text="一次上傳的所有檔案加總。擋的是「單檔都合格、但一次丟二十個」。",
                verbose_name="單次上傳合計上限（MB）",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="upload_max_compression_ratio",
            field=models.IntegerField(
                default=200,
                help_text="解開後大小 ÷ 壓縮後大小。正常簡報約 1:1（圖片本來就壓過了），壓縮炸彈動輒上千比一。",
                verbose_name="壓縮比上限",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="upload_max_file_mb",
            field=models.IntegerField(
                default=200,
                help_text="單一來源檔的大小上限。目前見過最大的真實簡報是 124MB，所以預設 200 留有餘裕。檔案上傳沒有內建上限，不設就是無上限。",
                verbose_name="單檔上限（MB）",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="upload_max_unpacked_mb",
            field=models.IntegerField(
                default=2048,
                help_text="pptx/docx 是 zip，抽圖時要解開。這是解開後的總量上限。",
                verbose_name="解開後總量上限（MB）",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="embed_device",
            field=models.CharField(
                choices=[
                    ("cuda", "GPU（快，但佔 ~2.3GB VRAM）"),
                    ("cpu", "CPU（釋出 VRAM 給生成模型；查詢只慢 ~44ms）"),
                ],
                default="cuda",
                help_text="嵌入模型（BGE-M3）跑在 GPU 還是 CPU。放 CPU 可騰出 ~2.3GB VRAM 給生成模型多一點餘裕，查詢僅慢約 44 毫秒；只有重建整個語料索引會明顯變慢。",
                max_length=8,
                verbose_name="本地嵌入模型執行裝置",
            ),
        ),
    ]
