# Generated by Django 5.2.13 on 2026-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0020_sitesettings_upload_max_batch_mb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="local_model_concurrency",
            field=models.IntegerField(
                default=1,
                help_text="同時可以打給本地模型的請求數——產稿、圖片辨識、抽取內容全部算在內。Ollama 一次只跑一個推論，排不上的請求會在它那邊等到逾時，所以這個閘門的用處是把等待留在我們這邊（等待免費），而不是留在 Ollama 那邊（等待會吃掉請求的逾時額度）。只在後端為本地模型時生效；線上 API 不受限制。",
                verbose_name="本地模型同時呼叫上限",
            ),
        ),
    ]
