# Generated by Django 5.2.13 on 2026-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0021_sitesettings_local_model_concurrency"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="extract_timeout_seconds",
            field=models.IntegerField(
                default=240,
                help_text="從簡報抽出內容、依自然語言更正、合併新檔案的上限。三檔案專案約 2 萬字，實測單次約 45 秒（模型暖機時）。",
                verbose_name="內容抽取逾時（秒）",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="generate_timeout_seconds",
            field=models.IntegerField(
                default=600,
                help_text="寫一篇稿、重寫一篇稿，以及方案 B 每個階段的單次上限。超過就放棄那次呼叫並標記失敗。",
                verbose_name="產稿逾時（秒）",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_timeout_seconds",
            field=models.IntegerField(
                default=120,
                help_text="辨識單張圖片的上限。本地視覺模型實測單張 13–28 秒。",
                verbose_name="圖片辨識逾時（秒）",
            ),
        ),
    ]
