# Generated by Django 5.2.13 on 2026-08-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0023_evaluation_judge_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("deepseek", "DeepSeek")],
                        default="openai",
                        max_length=16,
                        verbose_name="API 種類",
                    ),
                ),
                (
                    "base_url",
                    models.CharField(blank=True, max_length=300, verbose_name="端點"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="API Key"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="模型"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "線上模型",
                "verbose_name_plural": "線上模型",
                "ordering": ["pk"],
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="llm_backend",
            field=models.CharField(
                choices=[("online", "線上模型"), ("local", "本地模型")],
                default="online",
                help_text="只影響寫稿與圖片辨識，評審永遠走線上——避免本地模型評自己的稿子。",
                max_length=8,
                verbose_name="文字／圖片生成使用的 API",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="online_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="studio.onlineprovider",
                verbose_name="使用的線上模型",
            ),
        ),
    ]
