# Generated by Django 5.2.13 on 2026-08-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0024_onlineprovider_alter_sitesettings_llm_backend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="llm_backend",
            field=models.CharField(
                choices=[("online", "線上模型"), ("local", "本地模型")],
                default="online",
                help_text="寫稿、圖片辨識與評審都跟著這個設定。選本地時寫稿與評分是同一個模型，絕對分數意義有限，相對比較仍可用——每筆評分都記錄了當時的評分模型。",
                max_length=8,
                verbose_name="文字／圖片生成使用的模型",
            ),
        ),
    ]
