# Generated by Django 5.2.13 on 2026-08-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0026_seed_online_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="vision_backend",
            field=models.CharField(
                choices=[("online", "線上模型"), ("local", "本地模型")],
                default="online",
                help_text="只影響圖片辨識。與上面的文字模型各自獨立——本地的文字與視覺是兩個模型，這張卡上放不下兩個，分開設定才能一邊走本地、一邊走線上。",
                max_length=8,
                verbose_name="圖片辨識使用的模型",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_online_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="studio.onlineprovider",
                verbose_name="圖片使用的線上端點",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="llm_backend",
            field=models.CharField(
                choices=[("online", "線上模型"), ("local", "本地模型")],
                default="online",
                help_text="寫稿與評審跟著這個設定。選本地時寫稿與評分是同一個模型，絕對分數意義有限，相對比較仍可用——每筆評分都記錄了當時的評分模型。",
                max_length=8,
                verbose_name="文字生成使用的模型",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="online_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="studio.onlineprovider",
                verbose_name="文字使用的線上端點",
            ),
        ),
    ]
