# Generated by Django 5.2.13 on 2026-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0028_carry_vision_backend"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onlineprovider",
            options={
                "ordering": ["use", "pk"],
                "verbose_name": "線上模型",
                "verbose_name_plural": "線上模型",
            },
        ),
        migrations.AddField(
            model_name="onlineprovider",
            name="use",
            field=models.CharField(
                choices=[("text", "文字"), ("vision", "圖片")],
                default="text",
                max_length=8,
                verbose_name="用途",
            ),
        ),
    ]
