# Generated by Django 5.2.13 on 2026-08-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0029_alter_onlineprovider_options_onlineprovider_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineprovider",
            name="kind",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("deepseek", "DeepSeek"),
                    ("google", "Google Gemini"),
                ],
                default="openai",
                max_length=16,
                verbose_name="API 種類",
            ),
        ),
    ]
