# Generated by Django 5.2.13 on 2026-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0030_alter_onlineprovider_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineprovider",
            name="thinking",
            field=models.BooleanField(
                default=True,
                help_text="關閉可省下推理 token 與等待時間，代價是模型不再先想過再答。目前只有 DeepSeek v4 系列吃這個設定。",
                verbose_name="啟用思考模式",
            ),
        ),
    ]
