# Generated by Django 5.2.13 on 2026-08-11 12:37

from django.db import migrations, models


def carry_thinking(apps, schema_editor):
    """Keep existing DeepSeek rows behaving as they did.

    Thinking used to be a separate boolean that defaulted to on, and nothing
    in the UI ever turned it off — so every existing DeepSeek row was a
    thinking one. Plain "DeepSeek" now *means* non-thinking, so leaving the
    kind alone would silently switch those rows to the variant measured worst
    of everything tried (1.67 of 5, and a rewrite that gained nothing).
    """
    OnlineProvider = apps.get_model("studio", "OnlineProvider")
    OnlineProvider.objects.filter(kind="deepseek", thinking=True).update(
        kind="deepseek-thinking")


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0031_onlineprovider_thinking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineprovider",
            name="kind",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("deepseek", "DeepSeek"),
                    ("deepseek-thinking", "DeepSeek-thinking"),
                    ("google", "Google Gemini"),
                ],
                default="openai",
                max_length=32,
                verbose_name="API 種類",
            ),
        ),
        migrations.RunPython(carry_thinking, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="onlineprovider",
            name="thinking",
        ),
    ]
