# Generated by Django 5.2.13 on 2026-08-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0032_split_deepseek_thinking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineprovider",
            name="kind",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("deepseek", "DeepSeek"),
                    ("deepseek-thinking", "DeepSeek-thinking"),
                    ("google", "Google Gemini"),
                    ("kimi", "Kimi / Moonshot"),
                ],
                default="openai",
                max_length=32,
                verbose_name="API 種類",
            ),
        ),
    ]
