# Generated by Django 5.2.13 on 2026-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0033_add_kimi_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationrun",
            name="cached_input_tokens",
            field=models.IntegerField(default=0, verbose_name="命中快取的輸入 token"),
        ),
        migrations.AddField(
            model_name="generationrun",
            name="input_tokens",
            field=models.IntegerField(default=0, verbose_name="輸入 token"),
        ),
        migrations.AddField(
            model_name="generationrun",
            name="output_tokens",
            field=models.IntegerField(default=0, verbose_name="輸出 token"),
        ),
        migrations.AddField(
            model_name="generationrun",
            name="reasoning_tokens",
            field=models.IntegerField(
                default=0,
                help_text="計入輸出計費，但不出現在文字裡",
                verbose_name="推理 token",
            ),
        ),
        migrations.AddField(
            model_name="generationrun",
            name="usage_calls",
            field=models.IntegerField(default=0, verbose_name="API 呼叫次數"),
        ),
    ]
