# Generated by Django 5.2.13 on 2026-08-12 07:16

from django.db import migrations, models


def carry_openai_kind(apps, schema_editor):
    """Existing "openai" rows become the medium variant.

    Those rows sent no `reasoning.effort` at all, so they ran on OpenAI's own
    default. Measured 2026-08-12 on `gpt-5.6-sol`: sending nothing produced the
    same zero reasoning tokens as none/low/medium, and only `high` differed —
    so medium is the closest of the four and preserves behaviour.
    """
    OnlineProvider = apps.get_model("studio", "OnlineProvider")
    OnlineProvider.objects.filter(kind="openai").update(kind="openai-medium")


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0034_run_token_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineprovider",
            name="kind",
            field=models.CharField(
                choices=[
                    ("openai-none", "OpenAI（none）"),
                    ("openai-low", "OpenAI（low）"),
                    ("openai-medium", "OpenAI（medium）"),
                    ("openai-high", "OpenAI（high）"),
                    ("deepseek", "DeepSeek"),
                    ("deepseek-thinking", "DeepSeek-thinking"),
                    ("google", "Google Gemini"),
                    ("kimi", "Kimi / Moonshot"),
                ],
                default="openai",
                max_length=32,
                verbose_name="API 種類",
            ),
        ),
        migrations.RunPython(carry_openai_kind, migrations.RunPython.noop),
    ]
