# Generated by Django 5.2.13 on 2026-08-12 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0018_alter_brieffacts_source"),
        ("studio", "0035_openai_effort_kinds"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("extract", "抽取內容"),
                            ("classify", "分析圖片"),
                            ("generate", "產稿"),
                            ("refine", "重寫"),
                            ("judge", "評分"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="用途",
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=64, verbose_name="模型"),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="端點種類"
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "reasoning_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="已包含在輸出 token 內，另計只是為了看出比例",
                    ),
                ),
                ("cached_input_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.FloatField(default=0.0, verbose_name="金額（美元）"),
                ),
                (
                    "priced",
                    models.BooleanField(
                        default=True,
                        help_text="False 代表這個模型沒有定價資料，金額會是 0",
                        verbose_name="費率已知",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "brief",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to="briefs.brief",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to="studio.generationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token 用量",
                "verbose_name_plural": "Token 用量",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["brief", "purpose"],
                        name="studio_toke_brief_i_5836a9_idx",
                    ),
                    models.Index(
                        fields=["run", "purpose"], name="studio_toke_run_id_e4b348_idx"
                    ),
                ],
            },
        ),
    ]
