# Generated by Django 5.2.13 on 2026-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0036_token_usage_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenusage",
            name="items",
            field=models.IntegerField(default=0, verbose_name="涵蓋張數"),
        ),
    ]
