# Generated by Django 5.2.13 on 2026-07-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名稱')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='briefs/', verbose_name='簡報檔')),
                ('raw_text', models.TextField(blank=True, verbose_name='簡報純文字')),
                ('slide_count', models.IntegerField(default=0, verbose_name='投影片數')),
                ('facts', models.JSONField(blank=True, default=dict, verbose_name='結構化事實（唯一事實來源）')),
                ('status', models.CharField(choices=[('uploaded', '已上傳'), ('extracted', '已抽取，待確認'), ('confirmed', '已確認')], default='uploaded', max_length=16)),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '簡報',
                'verbose_name_plural': '簡報',
                'ordering': ['-created_at'],
            },
        ),
    ]
