# Generated by Django 6.0.4 on 2026-07-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0002_brief_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="BriefImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slide_index",
                    models.IntegerField(default=0, verbose_name="投影片頁次"),
                ),
                (
                    "file",
                    models.ImageField(upload_to="brief_images/", verbose_name="圖片"),
                ),
                (
                    "md5",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        verbose_name="精確雜湊",
                    ),
                ),
                (
                    "phash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=16,
                        verbose_name="感知雜湊",
                    ),
                ),
                (
                    "slide_heading",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="投影片標題"
                    ),
                ),
                (
                    "nearby_text",
                    models.TextField(
                        blank=True,
                        help_text="同張投影片上距離最近的文字。這是空間推測，不是簡報作者標註的圖說。",
                        verbose_name="鄰近文字（依位置推測）",
                    ),
                ),
                (
                    "ai_description",
                    models.TextField(blank=True, verbose_name="AI 描述"),
                ),
                (
                    "ai_category",
                    models.CharField(
                        choices=[
                            ("usable", "可用素材"),
                            ("layout", "表格／排版"),
                            ("decoration", "logo／裝飾"),
                            ("unknown", "未判斷"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="AI 分類",
                    ),
                ),
                (
                    "ai_caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="AI 建議圖說"
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="可用於稿件"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="留空就用 AI 建議的圖說。",
                        max_length=200,
                        verbose_name="圖說",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="briefs.brief",
                    ),
                ),
            ],
            options={
                "verbose_name": "簡報圖片",
                "verbose_name_plural": "簡報圖片",
                "ordering": ["slide_index", "pk"],
            },
        ),
    ]
