# Generated by Django 6.0.4 on 2026-07-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0003_briefimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="briefimage",
            name="ai_brand",
            field=models.CharField(
                blank=True,
                help_text="用來擋掉競品照。提案簡報前段常放對手商品做市場分析，那些不屬於本篇素材。",
                max_length=80,
                verbose_name="圖中辨識到的品牌",
            ),
        ),
    ]
