# Generated by Django 6.0.4 on 2026-07-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0004_briefimage_ai_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="parse_images",
            field=models.BooleanField(default=False, verbose_name="解析簡報圖片"),
        ),
    ]
