# Generated by Django 6.0.4 on 2026-07-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0005_brief_parse_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="BriefFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="該版結構化事實"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("extract", "上傳時抽取"),
                            ("user_update", "使用者更正"),
                        ],
                        default="extract",
                        max_length=16,
                        verbose_name="來源",
                    ),
                ),
                (
                    "user_input",
                    models.TextField(
                        blank=True,
                        help_text="原文照存。日後要檢討合併把什麼改壞了，這是唯一的證據。",
                        verbose_name="使用者當時輸入的更正",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_versions",
                        to="briefs.brief",
                    ),
                ),
            ],
            options={
                "verbose_name": "簡報事實版本",
                "verbose_name_plural": "簡報事實版本",
                "ordering": ["-version"],
                "unique_together": {("brief", "version")},
            },
        ),
    ]
