# Generated by Django 6.0.4 on 2026-07-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0007_seed_facts_v1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brieffacts",
            name="source",
            field=models.CharField(
                choices=[
                    ("extract", "上傳時抽取"),
                    ("user_update", "使用者更正"),
                    ("staff_edit", "管理者手動編輯"),
                ],
                default="extract",
                max_length=16,
                verbose_name="來源",
            ),
        ),
    ]
