# Generated by Django 6.0.4 on 2026-08-01 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0009_alter_brieffacts_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="brieffacts",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="briefs.brieffacts",
                verbose_name="以哪一版為基礎",
            ),
        ),
    ]
