# Generated by Django 6.0.4 on 2026-08-03 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0010_brieffacts_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="briefimage",
            name="slide_index",
            field=models.IntegerField(
                default=0,
                help_text="該來源檔案內的第幾頁/第幾張，不是跨檔案的絕對編號。",
                verbose_name="投影片頁次",
            ),
        ),
        migrations.CreateModel(
            name="BriefSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="briefs/", verbose_name="檔案"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pptx", "PowerPoint"),
                            ("docx", "Word"),
                            ("pdf", "PDF"),
                        ],
                        max_length=8,
                        verbose_name="格式",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="順序")),
                (
                    "raw_text",
                    models.TextField(blank=True, verbose_name="這份檔案的純文字"),
                ),
                (
                    "page_count",
                    models.IntegerField(default=0, verbose_name="頁數／投影片數"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理"),
                            ("processing", "處理中"),
                            ("done", "完成"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="錯誤訊息")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始處理時間"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="briefs.brief",
                    ),
                ),
            ],
            options={
                "verbose_name": "來源檔案",
                "verbose_name_plural": "來源檔案",
                "ordering": ["brief_id", "order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="briefimage",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="briefs.briefsourcefile",
                verbose_name="來自哪個來源檔案",
            ),
        ),
    ]
