# Generated by Django 6.0.4 on 2026-08-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0012_backfill_source_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brief",
            name="source_file",
        ),
    ]
