# Generated by Django 6.0.4 on 2026-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0013_remove_brief_source_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="processing",
            field=models.BooleanField(default=False, verbose_name="背景處理中"),
        ),
    ]
