# Generated by Django 6.0.4 on 2026-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0014_brief_processing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="briefimage",
            name="nearby_text",
            field=models.TextField(
                blank=True,
                help_text="簡報是同一張投影片上距離最近的文字（空間推測）；Word 是圖片前後的段落（順序推測）。兩者都不是作者標註的圖說。",
                verbose_name="鄰近文字（依位置推測）",
            ),
        ),
        migrations.AlterField(
            model_name="briefimage",
            name="slide_heading",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="所在段落／投影片標題"
            ),
        ),
        migrations.AlterField(
            model_name="briefimage",
            name="slide_index",
            field=models.IntegerField(
                default=0,
                help_text="該來源檔案內的第幾張投影片／第幾段／第幾頁，依格式而定，不是跨檔案的絕對編號。",
                verbose_name="來源檔案內位置",
            ),
        ),
    ]
