# Generated by Django 6.0.4 on 2026-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0015_alter_briefimage_nearby_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="briefimage",
            name="is_manual",
            field=models.BooleanField(
                default=False,
                help_text="操作者直接上傳的素材（例如代言人照、新拍的產品照），不是從簡報抽出來的，沒有 source_file／slide_index 可言。",
                verbose_name="使用者手動上傳",
            ),
        ),
    ]
